export const pt = {
  nav: { shop: 'Loja', build: 'Criar Caixa', journal: 'Blog', about: 'Sobre', contact: 'Contacto', account: 'Conta', login: 'Entrar', cart: 'Carrinho' },
  brand: { tagline: 'Caixas de subscrição para cães e gatos' },
  home: {
    eyebrow: 'Cães + gatos • subscrição + compras únicas',
    title: 'Uma caixa surpresa feita à medida do seu melhor amigo.',
    subtitle: 'A PetBox entrega brinquedos, snacks e acessórios escolhidos para o perfil do seu cão ou gato. Escolha um plano mensal ou trimestral, personalize a caixa e receba tudo em casa.',
    primaryCta: 'Criar a minha caixa', secondaryCta: 'Ver produtos',
    stats: ['Planos mensais e trimestrais', 'Para cães e gatos', 'Personalização simples'],
    plansEyebrow: 'Planos', plansTitle: 'Escolha a frequência ideal', addonsEyebrow: 'Extras', addonsTitle: 'Favoritos para juntar à caixa',
    whyEyebrow: 'Experiência', whyTitle: 'Pensado para donos ocupados e animais felizes',
    whyText: 'A navegação é simples, o configurador guia cada escolha e o checkout é directo. O objectivo é reduzir dúvidas e aumentar confiança antes da compra.',
    mockupEyebrow: 'UX', mockupTitle: 'Fluxo desenhado para conversão',
    mockupText: 'Início → Criar Caixa → Carrinho → Pagamento → Conta. Cada etapa usa chamadas para acção claras e feedback visual.'
  },
  common: { addToCart: 'Adicionar ao carrinho', view: 'Ver', checkout: 'Finalizar compra', remove: 'Remover', total: 'Total', subtotal: 'Subtotal', shipping: 'Envio', summary: 'Resumo', quantity: 'Quantidade', save: 'Guardar', loading: 'A carregar...', close: 'Fechar' },
  configure: { eyebrow: 'Configurador', title: 'Crie a caixa ideal para o seu animal', intro: 'Um processo em passos simples: animal, tamanho, plano, personalidade e extras.', steps: ['Animal', 'Tamanho', 'Plano', 'Estilo', 'Extras'], petType: 'Tipo de animal', petSize: 'Tamanho', delivery: 'Plano de entrega', theme: 'Personalidade da caixa', extras: 'Extras opcionais', dog: 'Cão', cat: 'Gato', small: 'Pequeno', medium: 'Médio', large: 'Grande', monthly: 'Mensal', quarterly: 'Trimestral', playful: 'Brincalhão', cozy: 'Conforto', outdoor: 'Aventura', calm: 'Calmo', treats: 'Snacks extra', toyUpgrade: 'Brinquedo premium', careItem: 'Produto de cuidado', photoAccessory: 'Acessório para fotos', liveSummary: 'Resumo em tempo real', add: 'Adicionar caixa', buy: 'Comprar agora' },
  contact: { eyebrow: 'Contacto', title: 'Fale com a equipa PetBox', intro: 'Envie uma mensagem e ela será encaminhada para o email do projecto.', name: 'O seu nome', email: 'Email', subject: 'Assunto', message: 'Como podemos ajudar?', send: 'Enviar mensagem', success: 'Mensagem enviada com sucesso.', fallback: 'Não foi possível enviar a mensagem. Verifique as variáveis de email no Vercel.' },
  pages: { shopTitle: 'Loja de produtos para animais', shopIntro: 'Snacks, brinquedos e acessórios que podem ser comprados uma só vez ou adicionados à sua subscrição.', cartTitle: 'Revise as escolhas para o seu animal', checkoutTitle: 'Pagamento seguro com Stripe', accountTitle: 'Gerir conta, subscrição e pagamento', aboutEyebrow: 'Sobre', aboutTitle: 'Criada para momentos de unboxing mais felizes', aboutText: 'A PetBox é uma plataforma de comércio electrónico pensada para caixas de subscrição para animais. Combina planos mensais e trimestrais, personalização por perfil do animal, produtos avulsos e integração com Stripe.', journalTitle: 'Blog PetBox', journalIntro: 'Dicas de cuidados, brincadeiras e inspiração para donos de cães e gatos.' },
  account: { subscription: 'Subscrição', status: 'Estado', customer: 'Cliente Stripe', subscriptionId: 'ID da subscrição', noSubscription: 'Ainda não existe subscrição', notConnected: 'Ainda não ligado', manage: 'Gerir subscrição', billing: 'Atualizar pagamento', completeCheckout: 'Conclua primeiro um checkout Stripe para associar este cliente.', recentOrders: 'Encomendas recentes', noOrders: 'Ainda não existem encomendas de demonstração.', authTitle: 'Área de cliente', authIntro: 'Crie conta ou entre para simular uma área de cliente com backend Supabase.', email: 'Email', password: 'Palavra-passe', signIn: 'Entrar', signUp: 'Criar conta', signOut: 'Terminar sessão', signedInAs: 'Sessão iniciada como' },
  checkout: { title: 'Checkout', intro: 'O Stripe trata dos dados de pagamento de forma segura.', firstName: 'Nome', lastName: 'Apelido', email: 'Email', address: 'Morada', city: 'Cidade', zip: 'Código postal', pay: 'Pagar com Stripe', redirecting: 'A redireccionar...' },
  cart: { emptyTitle: 'O carrinho está vazio', emptyText: 'Adicione uma caixa, um snack ou um produto avulso para começar.', shopNow: 'Ir para a loja', subscription: 'Subscrição', customBox: 'Caixa personalizada', product: 'Produto', orderSummary: 'Resumo da encomenda', orderText: 'O envio é calculado de forma simples para a demonstração. Subscrições e produtos avulsos podem ser comprados juntos.' }
};
